### ISSUE TITLE
Can this SeekBar be horizontal?

### ISSUE THREAD

**Issue by NeoLSN** [jiahuanyu/PopSeekBar#1]
It shows vertical in the sample.
Can it be horizontal?

**Comment by Lir10** [comment]
just add 
android:rotation="90"
to the seekbar xml

**Comment by enginarslan** [comment]
can use it thumb drawable?

**Comment by jiahuanyu** [comment]
No yet now, but u can make some change of the code, it is not very difficult. It's not a very complete library. Sorry for that, but i will try to make some available time to make the view more convenient to use
